### ISSUE TITLE
执行 build.sh 报错

### ISSUE THREAD

**Issue by langgithub** [SeeFlowerX/unwinddaemon#2]
[ 97%] Linking CXX static library libunwindstack.a
[ 97%] Built target unwindstack
[ 98%] Building CXX object CMakeFiles/stackplz.dir/lib.cpp.o
[100%] Linking CXX shared library libstackplz.so
ld.lld: error: undefined symbol: async_safe_format_log_va_list
>>> referenced by LogAndroid.cpp:73 (/home/cozy/lang/android/aosp_12/system/extras/unwinddaemon/external/unwinding/libunwindstack/LogAndroid.cpp:73)
>>>               LogAndroid.cpp.o:(unwindstack::Log::AsyncSafe(char const*, ...)) in archive libunwindstack.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SeeFlowerX** [comment]
aosp？你用Android.bp试试。

如果你是自己改动过一些内容，还请详细说明一下，因为看起来不像是用的子模块方式

**Comment by SeeFlowerX** [comment]
这个错误可能是你编译设置的api等级太低。然后又没改对应log头文件导致的

可以调高最低sdk等级，或者自己手动去修改一下头文件，也不知道你把shim_files放哪儿去了……

**Comment by langgithub** [comment]
嗯

**Comment by langgithub** [comment]
add_library(libasync_safe STATIC
  "${EXTERNAL_SRC}/bionic/libc/async_safe/async_safe_log.cpp"
)

target_include_directories(libasync_safe
  PUBLIC
    ${EXTERNAL_SRC}/bionic/libc/async_safe/include
  PRIVATE
    ${EXTERNAL_SRC}/bionic/libc
)

target_include_directories(libasync_safe INTERFACE
  "${EXTERNAL_SRC}/bionic/libc/async_safe/include"
)

target_link_libraries(${PROJECT_NAME} log libasync_safe base procinfo lzma dexfile_support unwindstack)
加上头文件后正常了
